[Muffin] 이전 PR 내용 피드백 반영, 메인페이지 그리드 레이아웃 약간 수정
healtheloper/airbnb pull request #20
Opened 2022-05-26 13:04 UTC by Muffin9

1. 언급해주신 fd 네이밍 수정과 mock 데이터를 따로 분리하고 title를 포함시켰습니다!

2. Grid 작업을 좀 더 재사용있게 바꿔보려고 했는데.. 생각보다 잘 된건지는 모르겠네여
=> 약간 브라우저에서 사용할 수 있는 flex 속성을 재사용할 수 있께 FlexBox로 만든거 처럼 Material UI Grid를 GridBox로 만들어보았습니다.

unit(row마다 몇 개의 단위로 grid 형태를 이룰지) 파라미터를 넘겨 grid 컴포넌트 반응형이 되도록 했긴 했지만 매직넘버를 사용하지 않는다는점 말고는 딱히 좋아진점은 잘 모르겠네요..
=> unit 만 받아서 사용중인 GridBox, GridInnerBox가 괜히 불필요하게 컴포넌트를 빼낸거 같은 느낌도 드는거 같기도하고

파크의 생각은 어떤지 궁금합니다 .

2022-05-26 15:10 UTC, healtheloper requested changes
현재 코드가 어떻게 반응되는지 궁금한데, 제 레포에는 push 되어있지 않아서 코드추적이 어렵네요 ㅎㅎ
PR 에 간단히 움짤을 올리는건 너무 번거로운 작업일까요? 저는 giphy 라는 app 으로 움짤을 만들긴 하는데, 제가 먼저 올려보고 너무 귀찮다 싶으면 다시 말씀드릴게요,

GridBox 로 컴포넌트를 분리하기는 했지만, MainPage 에서 아래와 같이 사용되게 바꿀 순 없을까요?
```js
 <Box sx={{ width: '90rem', margin: '0 auto', padding: '0 5rem' }}>
    <Box sx={{ marginBottom: '5rem' }}>
      <Typography variant="h4" sx={{ marginBottom: '2rem' }}>
        {nearByData.title}
      </Typography>
      <GridBox unit={4} gridDatas={nearByData.infos} />
    </Box>

    <Box sx={{ marginBottom: '5rem' }}>
      <Typography variant="h4" sx={{ marginBottom: '2rem' }}>
        {anywhereData.title}
      </Typography>
      <GridBox unit={4} gridDatas={anyWhereData.infos} />
    </Box>
  </Box>
```

++)
#19 이슈에 대한 내용도 반영되어서 올리면 좋을 것 같습니다 ㅎㅎ

2022-05-26 15:10 UTC, healtheloper commented on src/components/GridBox.tsx
> +  const spacing = Math.floor(gridDefaultValue / unit);
GridBox 에서 unit 을 받으면
unit 의 갯수만큼만 박스를 받도록 할 것 같은데, unit 을 받아서 단순히 spacing 을 주는게 맞는지? 조금 헷갈리네요

2022-05-26 15:10 UTC, healtheloper commented on src/components/GridBox.tsx
> +  const sm = Math.floor((gridDefaultValue * 2) / unit);
해석하는데 시간이 좀 걸렸던 것 같아요,
lg 는 unit 갯수로 나뉘어서 12 를 갯수만큼 나누었으니 동일하게 grid 를 가져간다고 이해가 되지만
*2 를 한 순간에는 무슨의도인지 조금 헷갈릴 것 같아요. 만약 unit 이 2 라면 md 가 12가 되어 1 row 당 1 개의 component 만 존재하게 될건데,

unit 이 3 이라면 md, sm 이 8 을 가져가게 되는데,  결국 8 8 8 이러면 1 row 당 1 개의 component 를 가져가게 되지 않나요? (max 가 12 이니까)

2022-05-27 01:59 UTC, Muffin9 commented on src/components/GridBox.tsx
> +  const spacing = Math.floor(gridDefaultValue / unit);
unit 을 받아서 단순히 spacing 을 주도록 해야 할 것 같네요!
불필요한 로직을 작성한거 같아요

2022-05-27 02:02 UTC, Muffin9 commented on src/components/GridBox.tsx
> +  const sm = Math.floor((gridDefaultValue * 2) / unit);
그러네요.. 그리고 다시 생각해보니 현재 제가 만들어논거는 각 Grid안의 컴포넌트 xs, sm, md lg, xl 각 사이즈일때 값이 유동적이지 않고 딱 떨어지고 있어서, 그냥 기존 Grid 컴포넌트 구조를 가져가는게 좋다고 생각하네요
GridBox, GridInnerBox  로 그냥 분리하지말고 Material UI 에서 제공하는 Grid를 가져다가 쓰는게 더 좋을 것 같아요
메인에서 사용되어지는 컴포넌트 분리만 해놓는게 좋을듯 싶어요 다시 코드 수정해서 푸쉬할게요~

2022-05-27 03:10 UTC, merged